services:
  app:
    build: .
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=development
    command: uvicorn backend.app:app --host=0.0.0.0 --port=8000 --reload
